app1:
  build: .
  hostname: app1
  links:
    - redis
  ports:
    - "8081:8080"

app2:
  build: .
  hostname: app2
  links:
    - redis
  ports:
    - "8082:8080"

redis:
  image: redis
  hostname: redis
  ports:
    - "6379:6379"